# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27f0bfe6d1a6ade7df31f59f3f8f8cf1a28271a0af713a03b90bb1b8b2aa4e535e046324d1073574bf129cbb4fd4564e0116623170618ffaa1b5fccf0cbc595f

test:
  secret_key_base: 5ba0c13f5df01ca78df5845a42a949f651bd4e0027744e313de9919acfb615356b8e4d2f59355cfbcf3ef29d903f04d9563d617faccb618f118c052eccde1778

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
